### ISSUE TITLE
Bio gif

### ISSUE THREAD

**Issue by VinayakBector2002** [matyo91/matyo91#4]
Hey Mathieu Ledru!
Firstly you have a really awesome readme!! I absolutely love it 🥇 
https://github.com/matyo91/matyo91/blob/main/assets/github.gif
I wanna make a gif like this as well and seek you advise on the same. 
Thanks in advance 
Best Regards
Bector

**Comment by matyo91** [comment]
Hi @VinayakBector2002.

Thanks for your great interest on my GitHub profile.
If you closely read the Readme.md, I described in comment below the gif how I done the gif. You can reproduce it as well. So  I recommend you to read the raw Readme and I will be glad to get feedback if something is not clear.

**Comment by VinayakBector2002** [comment]
Got it, thank you so much 👍

**Comment by VinayakBector2002** [comment]
Now my profile looks like this 😄 

https://github.com/VinayakBector2002

Hope you like it!
Regards

**Comment by matyo91** [comment]
Great profile. I like the 3d timeline contribution ! Best wishes for your covid model development.

**Comment by angelmtztrc** [comment]
Hey bro! How I can make a gif like yours?
